# Thymeleaf
spring:
  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
# H2 portal http://localhost:8080/h2-console
  h2:
    console:
      enabled: true

# H2 db setting
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    name: test
#    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true
   